// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjlQw5v9REgYpl5I8Gv6AakqZ_IRDOOhI',
    appId: '1:600865910485:web:4e11be77982b00d5833c5c',
    messagingSenderId: '600865910485',
    projectId: 'task1-b8f5f',
    authDomain: 'task1-b8f5f.firebaseapp.com',
    storageBucket: 'task1-b8f5f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbNXN6YUn3si8d_p9E9QtfDbtxlUjmkyY',
    appId: '1:600865910485:android:970b63966464e7e1833c5c',
    messagingSenderId: '600865910485',
    projectId: 'task1-b8f5f',
    storageBucket: 'task1-b8f5f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRvboaraOuLzy4hNp-Qv-0ulaYM1TSqlI',
    appId: '1:600865910485:ios:da2ed85eff63f1fd833c5c',
    messagingSenderId: '600865910485',
    projectId: 'task1-b8f5f',
    storageBucket: 'task1-b8f5f.firebasestorage.app',
    iosBundleId: 'com.example.task2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjlQw5v9REgYpl5I8Gv6AakqZ_IRDOOhI',
    appId: '1:600865910485:web:88ea0afab9a37d48833c5c',
    messagingSenderId: '600865910485',
    projectId: 'task1-b8f5f',
    authDomain: 'task1-b8f5f.firebaseapp.com',
    storageBucket: 'task1-b8f5f.firebasestorage.app',
  );
}
