// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBo-SS8Bw-W-zkyBjUIDsWVgdJ4DBj-vqI',
    appId: '1:208481706332:web:86088c3af9ed7f681ea199',
    messagingSenderId: '208481706332',
    projectId: 'proovidertask',
    authDomain: 'proovidertask.firebaseapp.com',
    databaseURL: 'https://proovidertask-default-rtdb.firebaseio.com',
    storageBucket: 'proovidertask.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7HusyMi2upsdN8YNR1Z4U0jaToXTVCm4',
    appId: '1:208481706332:android:dcb2b1f1e08de0e31ea199',
    messagingSenderId: '208481706332',
    projectId: 'proovidertask',
    databaseURL: 'https://proovidertask-default-rtdb.firebaseio.com',
    storageBucket: 'proovidertask.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAH-j4FNG2M2qiFTxDcUZtiiLsQM_491IQ',
    appId: '1:208481706332:ios:33506a53f701380d1ea199',
    messagingSenderId: '208481706332',
    projectId: 'proovidertask',
    databaseURL: 'https://proovidertask-default-rtdb.firebaseio.com',
    storageBucket: 'proovidertask.firebasestorage.app',
    iosBundleId: 'com.example.providetask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAH-j4FNG2M2qiFTxDcUZtiiLsQM_491IQ',
    appId: '1:208481706332:ios:33506a53f701380d1ea199',
    messagingSenderId: '208481706332',
    projectId: 'proovidertask',
    databaseURL: 'https://proovidertask-default-rtdb.firebaseio.com',
    storageBucket: 'proovidertask.firebasestorage.app',
    iosBundleId: 'com.example.providetask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBo-SS8Bw-W-zkyBjUIDsWVgdJ4DBj-vqI',
    appId: '1:208481706332:web:bbfae7c16ffb2b321ea199',
    messagingSenderId: '208481706332',
    projectId: 'proovidertask',
    authDomain: 'proovidertask.firebaseapp.com',
    databaseURL: 'https://proovidertask-default-rtdb.firebaseio.com',
    storageBucket: 'proovidertask.firebasestorage.app',
  );
}
