// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_v4VFghLJDt7fiDBKW3GDLtHHAvFAd1E',
    appId: '1:378482863619:web:0e7f0a9a622bcaf7d22836',
    messagingSenderId: '378482863619',
    projectId: 'internshiptask-f025b',
    authDomain: 'internshiptask-f025b.firebaseapp.com',
    databaseURL: 'https://internshiptask-f025b-default-rtdb.firebaseio.com',
    storageBucket: 'internshiptask-f025b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDL4NbRJnw8WvPUnmpajtIrCOaezMjw04A',
    appId: '1:378482863619:android:cd1af117d0850834d22836',
    messagingSenderId: '378482863619',
    projectId: 'internshiptask-f025b',
    databaseURL: 'https://internshiptask-f025b-default-rtdb.firebaseio.com',
    storageBucket: 'internshiptask-f025b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAX8S03exkGmKu_fhB2aaBP9Fp0k9i8_GQ',
    appId: '1:378482863619:ios:b27fdab3aa7b9b2ad22836',
    messagingSenderId: '378482863619',
    projectId: 'internshiptask-f025b',
    databaseURL: 'https://internshiptask-f025b-default-rtdb.firebaseio.com',
    storageBucket: 'internshiptask-f025b.firebasestorage.app',
    iosBundleId: 'com.example.firebasetask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAX8S03exkGmKu_fhB2aaBP9Fp0k9i8_GQ',
    appId: '1:378482863619:ios:b27fdab3aa7b9b2ad22836',
    messagingSenderId: '378482863619',
    projectId: 'internshiptask-f025b',
    databaseURL: 'https://internshiptask-f025b-default-rtdb.firebaseio.com',
    storageBucket: 'internshiptask-f025b.firebasestorage.app',
    iosBundleId: 'com.example.firebasetask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_v4VFghLJDt7fiDBKW3GDLtHHAvFAd1E',
    appId: '1:378482863619:web:8094cb3d1971c153d22836',
    messagingSenderId: '378482863619',
    projectId: 'internshiptask-f025b',
    authDomain: 'internshiptask-f025b.firebaseapp.com',
    databaseURL: 'https://internshiptask-f025b-default-rtdb.firebaseio.com',
    storageBucket: 'internshiptask-f025b.firebasestorage.app',
  );
}
